### ISSUE TITLE
The App needs more structure

### ISSUE THREAD

**Issue by sebastian-meier** [sebastian-meier/frontal#10]
So far its more like a crazy collection of bits and pieces...

**Comment by fabiantheblind** [comment]
e.g. like this:  

    .
    ├── main.js
    ├── app
    │   ├── module-files.js
    │   └── module-update.js
    ├── .babelrc
    ├── .jshintrc
    ├── .etc
    ├── package.json
    └── views
        ├── container
        |   ├── chart-type-1.html
        |   ├── chart-type-2.html
        │   └── misc.html
        └── default-theme
            ├── chart-type-1.html
            ├── chart-type-2.html
            ├── chart-type-3.html
            ├── chart-type-4.html
            ├── css
            ├── images
            └── js
